on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: false

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - name: Setup Develocity for npm
        uses: Duhemm/develocity-actions/setup-npm@5ebf395ea37fadfab15c6508f9d6018b441e4f5b
        with:
          develocity-url: https://dv-helm-standalone-unstable-main.grdev.net
          develocity-access-key: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
          develocity-injection-enabled: true
          develocity-npm-agent-url-override: https://develocity-npm-pkgs.grdev.net/gradle-develocity-agent-3.0.0-branch-main-20251113145013.tgz
      - name: Install dependencies
        run: npm install
      - name: Run Lint
        run: npm run lint
      - name: Run tests
        run: npm test
      - name: Upload coverage to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        if: env.CODECOV_TOKEN != null
        uses: codecov/codecov-action@v4
        with:
          token: ${{ env.CODECOV_TOKEN }}
